import numpy as np
from utils import get_3D_plane, visualize_3d_points, project_3d_to_2d
from scipy.spatial.transform import Rotation
import cv2
import os

#load the points from the colmap text file
all_data = np.loadtxt("sparse_text/points3D.txt", usecols=(1, 2, 3, 4, 5, 6), comments="#")
pts = all_data[:, :3]
rgb = all_data[:, 3:]
#run ransac for a few thousand iterations
#threshold needs to be decided...will do trial n error..
threshold = np.ptp(pts, axis=0).max() * 0.01
# threshold = 0.05
table_inliers, plane_normal = get_3D_plane(pts, 2000, threshold)

#save the inlier indices so we can color them differently later
np.save("inlier_indices.npy", table_inliers)
print(f"found {len(table_inliers)} inliers for the dominant plane")

# visualize_3d_points(pts, colors=rgb, inlier_indices=table_inliers)

'''
Now, make this plane the Z=0 axis, and "center" of this plane the origin of the new xyz coordinate system
'''

inlier_pts = pts[table_inliers] #points found by ransac
new_origin = np.mean(inlier_pts, axis=0) #o
z_local = plane_normal
z_local = plane_normal / np.linalg.norm(plane_normal)
dummy = np.array([1, 0, 0])
if np.abs(np.dot(z_local, dummy)) > 0.9: #handle edge case
    dummy = np.array([0, 1, 0])
    
x_local = np.cross(dummy, z_local)
x_local /= np.linalg.norm(x_local)
y_local = np.cross(z_local, x_local) #just cross prod.

#rotation matrix
R_local_to_scene = np.column_stack((x_local, y_local, z_local)) #stacking hte basis vectors as columns

print("transformation done. origin is centered in the inliers.")


'''
now, the icosahedron part..
'''
vertices = np.loadtxt('icosahedron.txt', comments=['#', 'f'], usecols=(1, 2, 3)) #need rgb too..
faces = np.loadtxt('icosahedron.txt', comments=['#', 'v'], usecols=(1, 2, 3), dtype=int) - 1

bottom_indices = np.where(np.abs(vertices[:, 2]) < 1e-6)[0] #checking z coordinate
bottom_center = np.mean(vertices[bottom_indices, :2], axis=0)

vertices[:, 0] -= bottom_center[0]
vertices[:, 1] -= bottom_center[1]

scale = 1 #adjust this until it looks right
vertices *= scale

scene_vertices = (R_local_to_scene @ vertices.T).T + new_origin
print("icosahedron placed and transformed into scene/physical space.")

#visualizing the icosahedron
# visualize_3d_points(pts, colors=rgb, inlier_indices=table_inliers, mesh_vertices=scene_vertices, mesh_faces=faces)


'''
now read camera params, generated by colmap
'''
cam_data = np.loadtxt('sparse_text/cameras.txt', comments='#', usecols=(2, 3, 4, 5, 6, 7))
cam_data = np.squeeze(cam_data)

width = cam_data[0]
height = cam_data[1]
focal_length = cam_data[2]
cx = cam_data[3]
cy = cam_data[4]
radial_distortion = cam_data[5]

print(f"intrinsic params of camera -> focal length: {focal_length}, camera center: ({cx}, {cy})")

#read external params
with open('sparse_text/images.txt', 'r') as file:
    lines = file.read().strip().split('\n')

#pose params
pose_lines = lines[4::2]

#format seems to be: IMAGE_ID, QW, QX, QY, QZ, TX, TY, TZ, CAMERA_ID, IMAGE_NAME_STRING
#'q': quarternion for rotation..
external_data = np.loadtxt(pose_lines, usecols=(0, 1, 2, 3, 4, 5, 6, 7))

image_ids = external_data[:, 0]
quaternions_wxyz = external_data[:, 1:5]
translations = external_data[:, 5:8]

#getting rotation matrices
quaternions_xyzw = np.column_stack((quaternions_wxyz[:, 1:4], quaternions_wxyz[:, 0]))
rotations = Rotation.from_quat(quaternions_xyzw).as_matrix()

print(f"loaded {len(image_ids)} camera poses.")
print(f"shape of rotation matrix: {rotations.shape} (N, 3, 3)")
print(f"shape of translation matrix: {translations.shape} (N, 3)")


'''
doing the 3d to 2d projection
'''
K = np.array([
    [focal_length, 0, cx],
    [0, focal_length, cy],
    [0, 0, 1]
])

output_folder = "ar_output"
if not os.path.exists(output_folder):
    os.makedirs(output_folder)
    
image_names = [line.split()[-1] for line in pose_lines]

np.random.seed(42)
face_colors = np.random.randint(50, 255, size=(len(faces), 3)).tolist()

for i in range(len(image_ids)):
    img_name = image_names[i]
    R_ext = rotations[i]
    t_ext = translations[i]
    
    #load the original photo
    img_path = os.path.join("images", img_name)
    if not os.path.exists(img_path): continue
    frame = cv2.imread(img_path)
    
    #do projection
    pixels, depths = project_3d_to_2d(scene_vertices, R_ext, t_ext, K)
    
    
    #"painter algo"
    face_depths = []
    for face in faces:
        min_depth = np.min([depths[face[0]], depths[face[1]], depths[face[2]]])
        face_depths.append(min_depth)
        
    sorted_face_indices = np.argsort(face_depths)[::-1]
    
    for face_idx in sorted_face_indices:
        face = faces[face_idx]
        color = face_colors[face_idx]
        
        #3 coords per triangle
        pt1 = pixels[face[0]].astype(int)
        pt2 = pixels[face[1]].astype(int)
        pt3 = pixels[face[2]].astype(int)
        
        if depths[face[0]] < 0 or depths[face[1]] < 0 or depths[face[2]] < 0:
            continue
            
        triangle_cnt = np.array([pt1, pt2, pt3])
        
        cv2.drawContours(frame, [triangle_cnt], 0, color, -1)
        #black border
        cv2.drawContours(frame, [triangle_cnt], 0, (0,0,0), 2)
        
    cv2.imwrite(os.path.join(output_folder, img_name), frame)

print("AR rendering complete! check the 'ar_output' folder.")